spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservice-config-cruii-dev
---
spring:
  profiles: test
  application:
    name: microservice-config-cruii-test