server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://s1:10010/eureka/, http://s2:10011/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: lagou-gateway
  cloud:
    gateway:
      routes:
        - id: autodeiver-service-router
          uri: lb://lagou-autodeliver-openfeign
          predicates:
            - Path=/autodeliver/**
        - id: resume-service-router
          uri: lb://lagou-resume
          predicates:
            - Path=/resumes/**
  rabbitmq:
    host: hk2
    port: 5672
    username: admin
    password: admin
ip:
  blacklist:
    - 192.168.0.1
    - 127.0.0.1
info: beijing,chengdu,shanghai,hangzhou,chongqing
