server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://s1:10010/eureka/, http://s2:10011/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: lagou-gateway
  zipkin:
    base-url: http://127.0.0.1:9411 # zipkin server的请求地址 sender:
      # web 客户端将踪迹日志数据通过网络请求的方式传送到服务端，另外还有配 置
      # kafka/rabbit 客户端将踪迹日志数据传递到mq进行中转
    sender:
      type: web
  sleuth:
    sampler:
      # 采样率 1 代表100%全部采集 ，默认0.1 代表10% 的请求踪迹数据会被采集
      # 生产环境下，请求量非常大，没有必要所有请求的踪迹数据都采集分析，对于网络包括server端压力都是比较大的，可以配置采样率采集一定比例的请求的踪迹 数据进行分析即可
      probability: 1
  cloud:
    gateway:
      routes:
        - id: autodeiver-service-router
          uri: lb://lagou-autodeliver-openfeign
          predicates:
            - Path=/autodeliver/**
        - id: resume-service-router
          uri: lb://lagou-resume
          predicates:
            - Path=/resumes/**
  rabbitmq:
    host: hk2
    port: 5672
    username: admin
    password: admin
ip:
  blacklist:
    - 192.168.0.1
   
info: beijing,chengdu,shanghai,hangzhou,chongqing
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
