spring: 
  profiles:
    active:
      - dev
---
server:
  port: 9098
spring:
  profiles: dev
  application:
    name: microservice-config-client
---
server:
  port: 9099
spring:
  profiles: test
  application:
    name: microservice-config-client
