spring:
  profiles:
    active:
      - dev
---
server:
  port: 7003

spring:
  profiles: dev
  application:
    name: microservice-config-eureka-client

eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/
